from __future__ import annotations

from pathlib import Path
from typing import Any


PROJECTS_ROOT = Path(__file__).resolve().parents[3]


PROJECT_BLUEPRINTS: list[dict[str, Any]] = [
    {
        "rank": 1,
        "id": "universal-ai",
        "name": "Universal AI / Sekhar AI OS",
        "motive": "Personal and professional installed-system assistant: a manager worker reads chat input, assigns expert workers, uses fully free/local-first tools, scouts the internet for better free technologies, can wrap fully free external tools that run locally or in the cloud, and evolves through approval-gated self-improvement.",
        "priority_reason": "Core brain that helps build and control the other projects.",
        "next_build": "Finish voice input/output, skill plugin registry, cursor highlight/teach mode, Hybrid/Graph/Corrective RAG checks, Finance Brain, and installer diagnostics.",
        "integration_role": "Central manager and orchestrator: LLM brain, RAG books, agent hands, MCP/tool connections, specialist workers, approvals, and automation workflows for all other projects.",
        "safety_boundary": "Risky actions require approval; destructive/security/payment/credential actions stay gated.",
        "free_tools": [
            "harper",
            "scrapegraphai",
            "gemma",
            "rank_bm25",
            "networkx",
            "sentence_transformers",
            "airllm",
            "mirofish",
            "kronos_finance",
            "n8n",
            "localsend",
            "local_repo_prompt_exporter",
            "homebrew",
            "git_cli_safety_workflow",
            "github_desktop",
            "exo_local_ai_cluster",
            "ray_local_cluster",
            "cosmos3",
            "hybrid_rag",
            "graph_rag",
            "agentic_rag",
            "corrective_rag",
            "automation_system",
        ],
        "path": str(PROJECTS_ROOT / "universal-ai"),
    },
    {
        "rank": 2,
        "id": "pcb-doctor",
        "name": "PCB Doctor",
        "motive": "AI repair assistant using camera, thermal camera, multimeter/programmer data, and guided diagnosis to find PCB faults and suggest repairs/design changes.",
        "priority_reason": "Most practical and commercially useful hardware/electronics product.",
        "next_build": "Add guided measurement workflows, PyVISA instrument hooks, thermal hotspot overlay, Multimodal RAG over datasheets/schematics/images, and repair report export.",
        "integration_role": "Universal AI can explain measurements, retrieve datasheets, guide repair steps, and generate reports.",
        "safety_boundary": "No unsafe bench power actions without user confirmation and current limiting.",
        "free_tools": [
            "scrapegraphai",
            "gemma",
            "local_repo_prompt_exporter",
            "git_cli_safety_workflow",
            "github_desktop",
            "sentence_transformers",
            "networkx",
            "multimodal_rag",
            "graph_rag",
            "piezoelectric_sensors",
            "cosmos3",
            "physical_ai_world_models",
            "localsend",
        ],
        "path": str(PROJECTS_ROOT / "pcb-doctor"),
    },
    {
        "rank": 3,
        "id": "ai-cyber-shield",
        "name": "AI Cyber Shield",
        "motive": "Defensive system guard that watches processes/network/system health, explains threats, reports evidence, and fixes safely with approval.",
        "priority_reason": "Protects the whole ecosystem and local AI machine.",
        "next_build": "Add process/network monitor, CCNA-style port/protocol checks, health dashboard, evidence reports, and approval-gated response actions.",
        "integration_role": "Protects Universal AI, plugins, microphone/audio permissions, project tools, local web servers, and automation adapters.",
        "safety_boundary": "Defensive only; no retaliation or exact-hacker-location claims beyond evidence/IP attribution limits.",
        "free_tools": [
            "the_book_of_secret_knowledge",
            "networkx",
            "gemma",
            "local_repo_prompt_exporter",
            "git_cli_safety_workflow",
            "github_desktop",
            "agentic_rag",
            "corrective_rag",
            "ccna_networking",
            "localsend",
        ],
        "path": str(PROJECTS_ROOT / "ai-cyber-shield"),
    },
    {
        "rank": 4,
        "id": "universal-translator",
        "name": "Universal Translator / ULT",
        "motive": "Real-time device-speaker-output translation with very low latency, preserving speaker identity/emotion/music as much as possible.",
        "priority_reason": "Huge potential but hardest engineering problem.",
        "next_build": "Ship live system-audio subtitle translation first, then add speech-to-text diagnostics, voice output, consent-safe speaker handling, and music-preserving mixing.",
        "integration_role": "Universal AI controls language/mode and Cyber Shield protects audio privacy.",
        "safety_boundary": "Voice preservation must be consent-based and clearly marked; no covert voice cloning.",
        "free_tools": [
            "gemma",
            "local_repo_prompt_exporter",
            "git_cli_safety_workflow",
            "github_desktop",
            "faster_whisper",
            "piper_tts",
            "openwakeword",
            "hardware_awareness",
            "localsend",
        ],
        "path": str(PROJECTS_ROOT / "universal-translator"),
    },
    {
        "rank": 5,
        "id": "musical-keyboard",
        "name": "Musical Keyboard",
        "motive": "Offline app that plays selected instrument notes for every keyboard/touch key press.",
        "priority_reason": "Fast to polish and useful as a low-risk audio/UI project.",
        "next_build": "Add record/replay, MIDI export, WAV export, sustain, octave controls, better samples, and optional piezo/pressure-sensor experiments.",
        "integration_role": "Universal AI can open it, change instruments, record, and suggest music ideas.",
        "safety_boundary": "Use copyright-safe/free samples.",
        "free_tools": [
            "piezoelectric_sensors",
            "localsend",
            "git_cli_safety_workflow",
            "github_desktop",
            "hardware_awareness",
            "free_programming_books",
        ],
        "path": str(PROJECTS_ROOT / "musical-keyboard"),
    },
    {
        "rank": 6,
        "id": "dews",
        "name": "DEWS / Defensive Early Warning System",
        "original_motive": "Originally imagined as a 'Weapon Destroyer' / directed-energy weapon-system concept: AI cameras, thermal sensing, and other sensors would detect weapons or ammunition at a distance, then a remote energy or metal-heating mechanism would attempt to disable the threat.",
        "motive": "Safe defensive early warning: camera/thermal hazard detection, restricted-zone alerts, evidence reports, and simulation.",
        "priority_reason": "Must stay in safe detection/simulation/alerting form.",
        "next_build": "Build webcam + thermal hazard detection, safe risk scoring, networked alerts, simulation, and incident report export.",
        "integration_role": "Universal AI explains alerts; Cyber Shield protects the device; PCB Doctor supports sensor hardware maintenance.",
        "safety_boundary": "Original weapon-disabling motive is history only. No destructive emitters, no weapon/ammunition/missile disablement, no targeting logic, no range optimization, and no autonomous engagement.",
        "free_tools": [
            "mirofish",
            "ccna_networking",
            "hardware_awareness",
            "piezoelectric_sensors",
            "git_cli_safety_workflow",
            "github_desktop",
            "cosmos3",
            "physical_ai_world_models",
            "agentic_rag",
            "localsend",
        ],
        "path": str(PROJECTS_ROOT / "dews"),
    },
    {
        "rank": 7,
        "id": "neuroseed",
        "name": "NeuroSeed",
        "original_motive": "Originally imagined as wireless information injection into the human brain to reduce education time, allowing people to spend more time understanding, practicing, and applying skills.",
        "motive": "Consent-first learning reinforcement using awake study, cue association, sleep-safe replay, and next-day recall checks.",
        "priority_reason": "Newest concept project; useful if kept science-grounded and privacy-first.",
        "next_build": "Polish the static prototype into a local study flow with AI lesson compression, flashcards, cue library, consent log, and morning recall tests.",
        "integration_role": "Universal AI can summarize lessons, generate recall questions, manage cue schedules, and keep ethical boundaries visible.",
        "safety_boundary": "Original brain-upload motive is history only. No memory upload claims, no unconscious persuasion, no unapproved sleep cueing, and no clinical claims without research review.",
        "free_tools": [
            "gemma",
            "harper",
            "local_repo_prompt_exporter",
            "git_cli_safety_workflow",
            "github_desktop",
            "sentence_transformers",
            "rank_bm25",
            "networkx",
            "localsend",
            "agent_loop",
            "automation_system",
        ],
        "path": str(PROJECTS_ROOT / "07-NeuroSeed"),
    },
]


def project_ecosystem() -> dict[str, Any]:
    projects = []
    for item in PROJECT_BLUEPRINTS:
        path = Path(item["path"])
        projects.append(
            {
                **item,
                "exists": path.exists(),
                "status": "present" if path.exists() else "missing",
            }
        )
    return {
        "strategy": "Build Universal AI first using the PDF ladder: LLM, RAG, agent, tool connections, approvals, automation, then use it as the central assistant for PCB Doctor, Cyber Shield, ULT, Musical Keyboard, safe DEWS, and NeuroSeed.",
        "build_first": "Sekhar AI OS v1: local-first chat, memory, Finance Brain, diagnostics, voice, project-aware free-tool mapping, and cursor-guided desktop assistant.",
        "free_tool_rule": "Everything mapped into the seven projects must be fully free: free/open-source/local-first where practical, with no paid or freemium service dependency in the core project plan. If a named tool is paid, freemium, trial-limited, reward-based, closed, or privacy-risky, first search for a similar fully free replacement and add only the replacement when it improves a project.",
        "projects": projects,
    }
