from __future__ import annotations

ENTITY_TYPES = {
    "PERSON", "PLACE", "ORGANIZATION", "OBJECT", "EVENT",
    "GOAL", "TASK", "PROJECT", "SKILL", "CONCEPT", "BELIEF", "PREFERENCE"
}

RELATION_TYPES = {
    "WORKS_AT", "OWNS", "USES", "LIKES", "CREATED",
    "SCHEDULED", "RELATED_TO", "PART_OF", "DEPENDS_ON",
    "CONFLICTS_WITH", "LOCATED_IN", "MEMBER_OF", "PREFERS"
}
