import os
import sys
import json
import time
import subprocess
import tempfile
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]

def kill_process_tree(pid: int):
    try:
        if sys.platform == "win32":
            subprocess.run(["taskkill", "/F", "/T", "/PID", str(pid)], capture_output=True)
        else:
            import psutil
            parent = psutil.Process(pid)
            for child in parent.children(recursive=True):
                child.kill()
            parent.kill()
    except Exception:
        pass

def run_shard(shard_data: dict, output_dir: Path, timeout_seconds: int = 300) -> dict:
    shard_id = shard_data["shard_id"]
    node_ids = shard_data["node_ids"]
    isolation_class = shard_data["isolation_class"]

    shard_dir = output_dir / "shards" / shard_id
    shard_dir.mkdir(parents=True, exist_ok=True)

    result_json_path = shard_dir / "pytest_results.json"

    env = dict(os.environ)
    env["KATTAPPA_TEST_MODE"] = "true"
    env["KATTAPPA_RESULT_JSON"] = str(result_json_path)

    shard_temp = Path(tempfile.gettempdir()) / f"kattappa_shard_{shard_id}_{int(time.time())}"
    shard_temp.mkdir(parents=True, exist_ok=True)
    env["KATTAPPA_DATA_DIR"] = str(shard_temp / "data")
    env["KATTAPPA_RUNTIME_DIR"] = str(shard_temp / "runtime")
    env["TEMP"] = str(shard_temp / "tmp")
    env["TMP"] = str(shard_temp / "tmp")

    plugin_rel_path = "scripts.validation.pytest_result_plugin"
    cmd = [sys.executable, "-m", "pytest", "-p", plugin_rel_path, "-v", "--tb=short"] + node_ids

    stdout_path = shard_dir / "stdout.log"
    stderr_path = shard_dir / "stderr.log"

    t0 = time.time()
    timed_out = False
    exit_code = -1

    with open(stdout_path, "w", encoding="utf-8") as out_f, open(stderr_path, "w", encoding="utf-8") as err_f:
        proc = subprocess.Popen(cmd, cwd=str(PROJECT_ROOT), stdout=out_f, stderr=err_f, env=env)
        root_pid = proc.pid

        try:
            exit_code = proc.wait(timeout=timeout_seconds)
        except subprocess.TimeoutExpired:
            timed_out = True
            kill_process_tree(root_pid)
            exit_code = -9

    duration = time.time() - t0

    # Load machine-readable result payload generated by KattappaResultPlugin
    executed_node_ids = []
    outcomes = {"passed": [], "failed": [], "errors": [], "skipped": [], "xfailed": [], "xpassed": []}
    collection_errors = []

    if result_json_path.exists():
        try:
            with open(result_json_path, "r", encoding="utf-8") as rf:
                plugin_data = json.load(rf)
                executed_node_ids = plugin_data.get("executed_node_ids", [])
                outcomes = plugin_data.get("outcomes", outcomes)
                collection_errors = plugin_data.get("collection_errors", [])
        except Exception as e:
            collection_errors.append(f"Failed to parse result JSON: {e}")

    shard_record = {
        "shard_id": shard_id,
        "isolation_class": isolation_class,
        "total_nodes_assigned": len(node_ids),
        "total_nodes_executed": len(executed_node_ids),
        "assigned_node_ids": node_ids,
        "executed_node_ids": executed_node_ids,
        "passed": len(outcomes["passed"]),
        "failed": len(outcomes["failed"]),
        "errors": len(outcomes["errors"]),
        "skipped": len(outcomes["skipped"]),
        "exit_code": exit_code,
        "timed_out": timed_out,
        "duration_seconds": round(duration, 2),
        "outcomes": outcomes,
        "collection_errors": collection_errors
    }

    with open(shard_dir / "shard-result.json", "w", encoding="utf-8") as f:
        json.dump(shard_record, f, indent=2)

    status_str = "TIMEOUT" if timed_out else ("PASS" if exit_code == 0 and len(outcomes['failed']) == 0 else "FAIL")
    print(f"[{shard_id}] {status_str} in {duration:.1f}s | Executed: {len(executed_node_ids)}/{len(node_ids)} | Passed: {len(outcomes['passed'])} | Failed: {len(outcomes['failed'])}")

    return shard_record
