from __future__ import annotations
from typing import Any

# Supported capability constants
CAP_SCREEN_READ = "CAP_SCREEN_READ"
CAP_SCREENSHOT = "CAP_SCREENSHOT"
CAP_MOUSE_MOVE = "CAP_MOUSE_MOVE"
CAP_KEYBOARD_INPUT = "CAP_KEYBOARD_INPUT"
CAP_FILE_READ = "CAP_FILE_READ"
CAP_FILE_WRITE = "CAP_FILE_WRITE"
CAP_FILE_CREATE = "CAP_FILE_CREATE"
CAP_FILE_DELETE = "CAP_FILE_DELETE"
CAP_WEB_SEARCH = "CAP_WEB_SEARCH"
CAP_WEB_DOWNLOAD = "CAP_WEB_DOWNLOAD"
CAP_TERMINAL_EXECUTE = "CAP_TERMINAL_EXECUTE"
CAP_MEMORY_WRITE = "CAP_MEMORY_WRITE"
CAP_TEST_EXECUTE = "CAP_TEST_EXECUTE"
CAP_BENCHMARK_EXECUTE = "CAP_BENCHMARK_EXECUTE"
CAP_CODE_ANALYZE = "CAP_CODE_ANALYZE"
CAP_CODE_GENERATE = "CAP_CODE_GENERATE"
CAP_CODE_PATCH = "CAP_CODE_PATCH"
CAP_PROPOSAL_CREATE = "CAP_PROPOSAL_CREATE"

# Voice capabilities
CAP_MICROPHONE_READ = "CAP_MICROPHONE_READ"
CAP_SPEAKER_OUTPUT = "CAP_SPEAKER_OUTPUT"
CAP_STT = "CAP_STT"
CAP_TTS = "CAP_TTS"
CAP_WAKE_WORD_DETECTION = "CAP_WAKE_WORD_DETECTION"

# Fine-grained memory capabilities
CAP_MEMORY_READ = "CAP_MEMORY_READ"
CAP_MEMORY_PIN = "CAP_MEMORY_PIN"
CAP_MEMORY_DELETE = "CAP_MEMORY_DELETE"
CAP_MEMORY_ROLLBACK = "CAP_MEMORY_ROLLBACK"

# Monitoring capabilities
CAP_MONITOR_CPU = "CAP_MONITOR_CPU"
CAP_MONITOR_RAM = "CAP_MONITOR_RAM"
CAP_MONITOR_GPU = "CAP_MONITOR_GPU"
CAP_MONITOR_STORAGE = "CAP_MONITOR_STORAGE"
CAP_MONITOR_NETWORK = "CAP_MONITOR_NETWORK"
CAP_MONITOR_TEMP = "CAP_MONITOR_TEMP"

# Agent Allowed/Denied Matrix
AGENT_CAPABILITIES = {
    "browser": {
        "allowed": {CAP_WEB_SEARCH, CAP_WEB_DOWNLOAD, CAP_SCREEN_READ, CAP_MEMORY_READ},
        "denied": {
            CAP_SCREENSHOT, CAP_MOUSE_MOVE, CAP_KEYBOARD_INPUT, 
            CAP_FILE_READ, CAP_FILE_WRITE, CAP_FILE_DELETE, 
            CAP_TERMINAL_EXECUTE, CAP_MEMORY_WRITE, CAP_MEMORY_PIN,
            CAP_MEMORY_DELETE, CAP_MEMORY_ROLLBACK
        }
    },
    "desktop": {
        "allowed": {
            CAP_SCREEN_READ, CAP_SCREENSHOT, CAP_MOUSE_MOVE, CAP_KEYBOARD_INPUT,
            CAP_FILE_DELETE, CAP_TERMINAL_EXECUTE, CAP_MEMORY_READ
        },
        "denied": {
            CAP_FILE_READ, CAP_FILE_WRITE, 
            CAP_WEB_SEARCH, CAP_WEB_DOWNLOAD, 
            CAP_MEMORY_WRITE, CAP_MEMORY_PIN, CAP_MEMORY_DELETE, CAP_MEMORY_ROLLBACK
        }
    },
    "file": {
        "allowed": {CAP_FILE_READ, CAP_FILE_WRITE, CAP_FILE_DELETE, CAP_FILE_CREATE, CAP_MEMORY_READ},
        "denied": {
            CAP_SCREEN_READ, CAP_SCREENSHOT, CAP_MOUSE_MOVE, CAP_KEYBOARD_INPUT,
            CAP_WEB_SEARCH, CAP_WEB_DOWNLOAD, CAP_TERMINAL_EXECUTE,
            CAP_MEMORY_WRITE, CAP_MEMORY_PIN, CAP_MEMORY_DELETE, CAP_MEMORY_ROLLBACK
        }
    },
    "researcher": {
        "allowed": {CAP_WEB_SEARCH, CAP_FILE_READ, CAP_MEMORY_READ},
        "denied": {
            CAP_SCREEN_READ, CAP_SCREENSHOT, CAP_MOUSE_MOVE, CAP_KEYBOARD_INPUT,
            CAP_FILE_WRITE, CAP_FILE_DELETE, CAP_WEB_DOWNLOAD,
            CAP_TERMINAL_EXECUTE, CAP_MEMORY_WRITE, CAP_MEMORY_PIN,
            CAP_MEMORY_DELETE, CAP_MEMORY_ROLLBACK
        }
    },
    "coder": {
        "allowed": {
            CAP_FILE_READ, CAP_FILE_WRITE, CAP_FILE_CREATE, CAP_FILE_DELETE,
            CAP_TEST_EXECUTE, CAP_BENCHMARK_EXECUTE, CAP_CODE_ANALYZE,
            CAP_CODE_GENERATE, CAP_CODE_PATCH, CAP_TERMINAL_EXECUTE, CAP_PROPOSAL_CREATE,
            CAP_MEMORY_READ, CAP_MEMORY_WRITE
        },
        "denied": {
            CAP_SCREEN_READ, CAP_SCREENSHOT, CAP_MOUSE_MOVE, CAP_KEYBOARD_INPUT,
            CAP_WEB_SEARCH, CAP_WEB_DOWNLOAD, CAP_MEMORY_PIN,
            CAP_MEMORY_DELETE, CAP_MEMORY_ROLLBACK
        }
    },
    "voice": {
        "allowed": {
            CAP_MICROPHONE_READ, CAP_SPEAKER_OUTPUT, CAP_STT, CAP_TTS,
            CAP_WAKE_WORD_DETECTION, CAP_FILE_READ, CAP_MEMORY_READ
        },
        "denied": {
            CAP_MEMORY_WRITE, CAP_SCREEN_READ, CAP_SCREENSHOT, CAP_MOUSE_MOVE, CAP_KEYBOARD_INPUT,
            CAP_WEB_SEARCH, CAP_WEB_DOWNLOAD, CAP_TERMINAL_EXECUTE, CAP_FILE_WRITE,
            CAP_FILE_CREATE, CAP_FILE_DELETE, CAP_MEMORY_PIN,
            CAP_MEMORY_DELETE, CAP_MEMORY_ROLLBACK
        }
    },
    "memory_service": {
        "allowed": {
            CAP_MEMORY_READ, CAP_MEMORY_WRITE, CAP_MEMORY_PIN,
            CAP_MEMORY_DELETE, CAP_MEMORY_ROLLBACK
        },
        "denied": set()
    },
    "planner": {
        "allowed": {CAP_MEMORY_READ, CAP_MEMORY_WRITE},
        "denied": {
            CAP_SCREEN_READ, CAP_SCREENSHOT, CAP_MOUSE_MOVE, CAP_KEYBOARD_INPUT,
            CAP_FILE_READ, CAP_FILE_WRITE, CAP_FILE_CREATE, CAP_FILE_DELETE,
            CAP_WEB_SEARCH, CAP_WEB_DOWNLOAD, CAP_TERMINAL_EXECUTE,
            CAP_MEMORY_PIN, CAP_MEMORY_DELETE, CAP_MEMORY_ROLLBACK
        }
    },
    "monitoring": {
        "allowed": {
            CAP_MONITOR_CPU, CAP_MONITOR_RAM, CAP_MONITOR_GPU,
            CAP_MONITOR_STORAGE, CAP_MONITOR_NETWORK, CAP_MONITOR_TEMP,
            CAP_MEMORY_READ, CAP_MEMORY_WRITE
        },
        "denied": {
            CAP_SCREEN_READ, CAP_SCREENSHOT, CAP_MOUSE_MOVE, CAP_KEYBOARD_INPUT,
            CAP_FILE_READ, CAP_FILE_WRITE, CAP_FILE_CREATE, CAP_FILE_DELETE,
            CAP_WEB_SEARCH, CAP_WEB_DOWNLOAD, CAP_TERMINAL_EXECUTE,
            CAP_MEMORY_PIN, CAP_MEMORY_DELETE, CAP_MEMORY_ROLLBACK
        }
    }
}

# Mapping of policy action keys to required capability
ACTION_CAPABILITY_MAP = {
    # File actions
    "READ_FILE": CAP_FILE_READ,
    "LIST_DIR": CAP_FILE_READ,
    "CREATE_FILE": CAP_FILE_CREATE,
    "WRITE_FILE": CAP_FILE_WRITE,
    "EDIT_FILE": CAP_FILE_WRITE,
    "DELETE_FILE": CAP_FILE_DELETE,
    "MOVE_FILE": CAP_FILE_WRITE,
    
    # Memory
    "SEARCH_MEMORY": CAP_MEMORY_READ,
    "RECALL_MEMORY": CAP_MEMORY_READ,
    "COMMIT_MEMORY_DELTA": CAP_MEMORY_WRITE,
    "PIN_MEMORY": CAP_MEMORY_PIN,
    "DELETE_MEMORY": CAP_MEMORY_DELETE,
    "ROLLBACK_MEMORY": CAP_MEMORY_ROLLBACK,
    "EXPIRE_MEMORY": CAP_MEMORY_WRITE,
    "CONSOLIDATE_MEMORY": CAP_MEMORY_WRITE,
    
    # Git / Shell / Packaging
    "GIT_COMMIT": CAP_FILE_WRITE,
    "GIT_PUSH": CAP_FILE_WRITE,
    "RUN_SHELL": CAP_TERMINAL_EXECUTE,
    "DEPLOY": CAP_TERMINAL_EXECUTE,
    "INSTALL_PACKAGE": CAP_TERMINAL_EXECUTE,
    "NETWORK_REQUEST": CAP_WEB_SEARCH,
    "SEND_EMAIL": CAP_WEB_SEARCH,
    "DESKTOP_CONTROL": CAP_MOUSE_MOVE,
    
    # Code actions
    "RUN_TESTS": CAP_TEST_EXECUTE,
    "RUN_BENCHMARKS": CAP_BENCHMARK_EXECUTE,
    "ANALYZE_CODE": CAP_CODE_ANALYZE,
    "GENERATE_CODE": CAP_CODE_GENERATE,
    "PATCH_CODE": CAP_CODE_PATCH,
    "CREATE_PROPOSAL": CAP_PROPOSAL_CREATE,
    "ANALYZE_REPO": CAP_CODE_ANALYZE,
    
    # Browser actions
    "BROWSER_SEARCH": CAP_WEB_SEARCH,
    "BROWSER_READ": CAP_WEB_SEARCH,
    "BROWSER_NAVIGATE": CAP_WEB_SEARCH,
    "BROWSER_MAP_LINKS": CAP_WEB_SEARCH,
    "BROWSER_EXTRACT_INFO": CAP_WEB_SEARCH,
    "BROWSER_DOWNLOAD_FILE": CAP_WEB_DOWNLOAD,
    "BROWSER_FILL_FORM": CAP_WEB_SEARCH,
    "BROWSER_CLICK_SUBMIT": CAP_WEB_SEARCH,
    "BROWSER_LOGIN": CAP_WEB_SEARCH,
    
    # Desktop actions
    "DESKTOP_READ_SCREEN": CAP_SCREEN_READ,
    "DESKTOP_SCREENSHOT": CAP_SCREENSHOT,
    "DESKTOP_OPEN_APP": CAP_MOUSE_MOVE,
    "DESKTOP_MOUSE_MOVE": CAP_MOUSE_MOVE,
    "DESKTOP_MOUSE_CLICK": CAP_MOUSE_MOVE,
    "DESKTOP_KEYBOARD_TYPING": CAP_KEYBOARD_INPUT,
    "DESKTOP_CLOSE_APP": CAP_MOUSE_MOVE,
    "DESKTOP_KILL_PROCESS": CAP_TERMINAL_EXECUTE,
    "DESKTOP_DELETE_FILE": CAP_FILE_DELETE,
    "DESKTOP_SHUTDOWN": CAP_TERMINAL_EXECUTE,
    "DESKTOP_SETTINGS": CAP_TERMINAL_EXECUTE,

    # Voice actions
    "VOICE_MICROPHONE_READ": CAP_MICROPHONE_READ,
    "VOICE_SPEAKER_OUTPUT": CAP_SPEAKER_OUTPUT,
    "VOICE_STT": CAP_STT,
    "VOICE_TTS": CAP_TTS,
    "VOICE_WAKE_WORD_DETECTION": CAP_WAKE_WORD_DETECTION,
    "COLLECT_METRICS": CAP_MONITOR_CPU,
}


class CapabilityRegistry:
    @staticmethod
    def is_capability_allowed(agent_name: str, capability: str) -> bool:
        agent = str(agent_name).lower().strip()
        if agent not in AGENT_CAPABILITIES:
            # Deny by default for unknown agents
            return False
        
        allowed = AGENT_CAPABILITIES[agent]["allowed"]
        denied = AGENT_CAPABILITIES[agent]["denied"]
        
        if capability in denied:
            return False
        return capability in allowed
