from __future__ import annotations

from pathlib import Path
from typing import Any

from backend.core.free_tool_catalog import developer_toolbox_audit


PROJECTS_ROOT = Path(__file__).resolve().parents[3]


PROJECT_BLUEPRINTS: list[dict[str, Any]] = [
    {
        "rank": 1,
        "id": "kattappa",
        "name": "Kattappa AI OS Assistant",
        "motive": "Personal and professional installed-system assistant: a manager worker reads chat input, assigns expert workers, uses fully free/local-first tools, scouts the internet for better free technologies, can wrap fully free external tools that run locally or in the cloud, and evolves through approval-gated self-improvement.",
        "priority_reason": "Core brain that helps build and control the other projects.",
        "next_build": "Finish voice input/output, skill plugin registry, cursor-highlight guidance, Hybrid/Graph/Corrective RAG checks, local eval harness, Second Brain/GOAT memory, Finance Brain, diagram generation, and installer diagnostics.",
        "integration_role": "Central manager and orchestrator: LLM brain, RAG books, agent hands, MCP/tool connections, specialist workers, approvals, and automation workflows for all other projects.",
        "safety_boundary": "Risky actions require approval; destructive/security/payment/credential actions stay gated.",
        "free_tools": [
            "harper",
            "scrapegraphai",
            "gemma",
            "rank_bm25",
            "networkx",
            "sentence_transformers",
            "airllm",
            "mirofish",
            "kronos_finance",
            "node_red",
            "localsend",
            "local_repo_prompt_exporter",
            "homebrew",
            "git_cli_safety_workflow",
            "github_desktop",
            "exo_local_ai_cluster",
            "ray_local_cluster",
            "deepseek_r1_local",
            "chromadb",
            "local_eval_harness",
            "ragas_or_deepeval_local",
            "mermaid",
            "excalidraw",
            "opencode_local_coding_loop",
            "qiskit",
            "local_b2b_playbook",
            "local_sovereign_frugal_ai_patterns",
            "cosmos3",
            "hybrid_rag",
            "graph_rag",
            "agentic_rag",
            "corrective_rag",
            "automation_system",
            "sqlite_builtin_backend",
            "pocketbase_optional_backend",
            "local_product_analytics",
            "local_workflow_queue",
            "local_multi_agent_orchestrator",
            "manual_export_billing_playbook",
        ],
        "path": str(PROJECTS_ROOT / "kattappa"),
    },
    {
        "rank": 2,
        "id": "pcb-doctor",
        "name": "PCB Doctor",
        "motive": "AI repair assistant using camera, thermal camera, multimeter/programmer data, and guided diagnosis to find PCB faults and suggest repairs/design changes.",
        "priority_reason": "Most practical and commercially useful hardware/electronics product.",
        "next_build": "Add guided measurement workflows, PyVISA instrument hooks, thermal hotspot overlay, Multimodal RAG over datasheets/schematics/images, Mermaid repair diagrams, local eval tests, and repair report export.",
        "integration_role": "Kattappa AI OS can explain measurements, retrieve datasheets, guide repair steps, and generate reports.",
        "safety_boundary": "No unsafe bench power actions without user confirmation and current limiting.",
        "free_tools": [
            "scrapegraphai",
            "gemma",
            "local_repo_prompt_exporter",
            "git_cli_safety_workflow",
            "github_desktop",
            "sentence_transformers",
            "networkx",
            "mermaid",
            "excalidraw",
            "local_eval_harness",
            "ragas_or_deepeval_local",
            "multimodal_rag",
            "graph_rag",
            "piezoelectric_sensors",
            "cosmos3",
            "physical_ai_world_models",
            "localsend",
            "sqlite_builtin_backend",
            "pocketbase_optional_backend",
            "local_product_analytics",
            "local_workflow_queue",
            "local_multi_agent_orchestrator",
        ],
        "path": str(PROJECTS_ROOT / "pcb-doctor"),
    },
    {
        "rank": 3,
        "id": "ai-cyber-shield",
        "name": "AI Cyber Shield",
        "motive": "Defensive system guard that watches processes/network/system health, explains threats, reports evidence, and fixes safely with approval.",
        "priority_reason": "Protects the whole ecosystem and local AI machine.",
        "next_build": "Add process/network monitor, CCNA-style port/protocol checks, health dashboard, evidence reports, local drill/eval harness, and approval-gated response actions.",
        "integration_role": "Protects Kattappa AI OS, plugins, microphone/audio permissions, project tools, local web servers, and automation adapters.",
        "safety_boundary": "Defensive only; no retaliation or exact-hacker-location claims beyond evidence/IP attribution limits.",
        "free_tools": [
            "the_book_of_secret_knowledge",
            "networkx",
            "gemma",
            "local_repo_prompt_exporter",
            "git_cli_safety_workflow",
            "github_desktop",
            "local_eval_harness",
            "local_sovereign_frugal_ai_patterns",
            "qiskit",
            "mermaid",
            "agentic_rag",
            "corrective_rag",
            "ccna_networking",
            "localsend",
            "sqlite_builtin_backend",
            "pocketbase_optional_backend",
            "local_product_analytics",
            "local_workflow_queue",
            "local_multi_agent_orchestrator",
        ],
        "path": str(PROJECTS_ROOT / "ai-cyber-shield"),
    },
    {
        "rank": 4,
        "id": "universal-translator",
        "name": "Universal Translator / ULT",
        "motive": "Real-time device-speaker-output translation with very low latency, preserving speaker identity/emotion/music as much as possible.",
        "priority_reason": "Huge potential but hardest engineering problem.",
        "next_build": "Ship live system-audio subtitle translation first, then add Vosk/faster-whisper STT diagnostics, Argos offline translation, Piper TTS, openWakeWord, consent-safe speaker handling, local eval tests, and music-preserving mixing.",
        "integration_role": "Kattappa AI OS controls language/mode and Cyber Shield protects audio privacy.",
        "safety_boundary": "Voice preservation must be consent-based and clearly marked; no covert voice cloning.",
        "free_tools": [
            "gemma",
            "local_repo_prompt_exporter",
            "git_cli_safety_workflow",
            "github_desktop",
            "faster_whisper",
            "piper_tts",
            "openwakeword",
            "argos_translate",
            "vosk",
            "local_eval_harness",
            "bhashini_research_only",
            "sarvam_free_llm_reference",
            "hardware_awareness",
            "localsend",
            "sqlite_builtin_backend",
            "pocketbase_optional_backend",
            "local_product_analytics",
            "local_workflow_queue",
            "local_multi_agent_orchestrator",
        ],
        "path": str(PROJECTS_ROOT / "universal-translator"),
    },
    {
        "rank": 5,
        "id": "musical-keyboard",
        "name": "Musical Keyboard",
        "motive": "Offline app that plays selected instrument notes for every keyboard/touch key press.",
        "priority_reason": "Fast to polish and useful as a low-risk audio/UI project.",
        "next_build": "Add record/replay, MIDI export, WAV export, sustain, octave controls, local eval smoke tests, Mermaid docs, better samples, and optional piezo/pressure-sensor experiments.",
        "integration_role": "Kattappa AI OS can open it, change instruments, record, and suggest music ideas.",
        "safety_boundary": "Use copyright-safe/free samples.",
        "free_tools": [
            "piezoelectric_sensors",
            "localsend",
            "git_cli_safety_workflow",
            "github_desktop",
            "mermaid",
            "local_eval_harness",
            "hardware_awareness",
            "free_programming_books",
            "local_product_analytics",
            "local_workflow_queue",
            "local_multi_agent_orchestrator",
        ],
        "path": str(PROJECTS_ROOT / "musical-keyboard"),
    },
    {
        "rank": 6,
        "id": "dews",
        "name": "DEWS / Defensive Early Warning System",
        "original_motive": "Originally imagined as a 'Weapon Destroyer' / directed-energy weapon-system concept: AI cameras, thermal sensing, and other sensors would detect weapons or ammunition at a distance, then a remote energy or metal-heating mechanism would attempt to disable the threat.",
        "motive": "Safe defensive early warning: camera/thermal hazard detection, restricted-zone alerts, evidence reports, and simulation.",
        "priority_reason": "Must stay in safe detection/simulation/alerting form.",
        "next_build": "Build webcam + thermal hazard detection, safe risk scoring, networked alerts, simulation, local safety eval drills, Mermaid incident diagrams, and incident report export.",
        "integration_role": "Kattappa AI OS explains alerts; Cyber Shield protects the device; PCB Doctor supports sensor hardware maintenance.",
        "safety_boundary": "Original weapon-disabling motive is history only. No destructive emitters, no weapon/ammunition/missile disablement, no targeting logic, no range optimization, and no autonomous engagement.",
        "free_tools": [
            "mirofish",
            "ccna_networking",
            "hardware_awareness",
            "piezoelectric_sensors",
            "git_cli_safety_workflow",
            "github_desktop",
            "local_eval_harness",
            "local_sovereign_frugal_ai_patterns",
            "mermaid",
            "cosmos3",
            "physical_ai_world_models",
            "agentic_rag",
            "localsend",
            "sqlite_builtin_backend",
            "pocketbase_optional_backend",
            "local_product_analytics",
            "local_workflow_queue",
            "local_multi_agent_orchestrator",
        ],
        "path": str(PROJECTS_ROOT / "dews"),
    },
    {
        "rank": 7,
        "id": "neuroseed",
        "name": "NeuroSeed",
        "original_motive": "Originally imagined as wireless information injection into the human brain to reduce education time, allowing people to spend more time understanding, practicing, and applying skills.",
        "motive": "Consent-first learning reinforcement using awake study, cue association, sleep-safe replay, and next-day recall checks.",
        "priority_reason": "Newest concept project; useful if kept science-grounded and privacy-first.",
        "next_build": "Polish the static prototype into a local study flow with Second Brain memory, AI lesson compression, flashcards, cue library, consent log, Mermaid/Excalidraw learning maps, and morning recall tests.",
        "integration_role": "Kattappa AI OS can summarize lessons, generate recall questions, manage cue schedules, and keep ethical boundaries visible.",
        "safety_boundary": "Original brain-upload motive is history only. No memory upload claims, no unconscious persuasion, no unapproved sleep cueing, and no clinical claims without research review.",
        "free_tools": [
            "gemma",
            "harper",
            "local_repo_prompt_exporter",
            "git_cli_safety_workflow",
            "github_desktop",
            "sentence_transformers",
            "rank_bm25",
            "networkx",
            "chromadb",
            "deepseek_r1_local",
            "mermaid",
            "excalidraw",
            "local_eval_harness",
            "qiskit",
            "local_sovereign_frugal_ai_patterns",
            "localsend",
            "agent_loop",
            "automation_system",
            "sqlite_builtin_backend",
            "pocketbase_optional_backend",
            "local_product_analytics",
            "local_workflow_queue",
            "local_multi_agent_orchestrator",
        ],
        "path": str(PROJECTS_ROOT / "07-NeuroSeed"),
    },
    {
        "rank": 8,
        "id": "kairo",
        "name": "KAIRO",
        "motive": "Telekinesis / Remote Matter Movement: Gesture-driven matter manipulation without physical contact by influencing objects remotely using combined technologies and invisible force interactions.",
        "priority_reason": "Enables remote gestural interaction and physical motion translation.",
        "next_build": "Build Leap Motion near-infrared hand-tracking array, gesture recognition neural net, electromagnetic coil field gradients, and acoustic levitation standing wave array.",
        "integration_role": "Kattappa AI OS coordinates gesture signals and triggers remote physical actuators.",
        "safety_boundary": "No high-voltage coil activation or unsafe levitation steps without physical feedback and current safety limits.",
        "free_tools": [
            "gemma",
            "git_cli_safety_workflow",
            "github_desktop",
            "local_eval_harness",
            "localsend",
            "sqlite_builtin_backend",
            "local_workflow_queue",
            "local_multi_agent_orchestrator",
            "mermaid",
        ],
        "path": str(PROJECTS_ROOT / "kairo"),
    },
    {
        "rank": 9,
        "id": "prism",
        "name": "PRISM",
        "motive": "Adaptive Invisible Shield: An intelligent envelope dome surrounding a person or object to stop physical threats, selectively manage and filter gases, and protect against extreme environmental dangers.",
        "priority_reason": "Defends physical assets and regulates survivability environments.",
        "next_build": "Integrate computer vision dynamic vector tracking, millimeter-wave radar, atmospheric chromatography monitoring, and pressurized HEPA gas filtering.",
        "integration_role": "Kattappa AI OS interprets threat warnings, routes telemetry to Cyber Shield, and operates safety barriers.",
        "safety_boundary": "Defensive alerting and atmospheric filtering only. Kinetic pulse deflectors must not hazard surrounding humans.",
        "free_tools": [
            "gemma",
            "git_cli_safety_workflow",
            "github_desktop",
            "local_eval_harness",
            "localsend",
            "sqlite_builtin_backend",
            "local_workflow_queue",
            "local_multi_agent_orchestrator",
            "mermaid",
        ],
        "path": str(PROJECTS_ROOT / "prism"),
    },
    {
        "rank": 10,
        "id": "tempo",
        "name": "TEMPO",
        "motive": "Temporal Dilation / Time Manipulation: A controlled localized environment where time flows differently from the outside world, enabling accelerated future travel through engineered relativistic temporal conditions.",
        "priority_reason": "Explores localized time speedups and relativistic spacetime physics.",
        "next_build": "Model mathematical spacetime geodesics, run relativistic gravity potential simulators, and measure centrifuge optical lattice clocks.",
        "integration_role": "Kattappa AI OS runs relativity models and collects precision clock calibration logs.",
        "safety_boundary": "Theoretical and modeling research only; energy density limits must prevent micro-gravity hazards.",
        "free_tools": [
            "gemma",
            "git_cli_safety_workflow",
            "github_desktop",
            "local_eval_harness",
            "localsend",
            "sqlite_builtin_backend",
            "local_workflow_queue",
            "local_multi_agent_orchestrator",
            "mermaid",
        ],
        "path": str(PROJECTS_ROOT / "tempo"),
    },
    {
        "rank": 11,
        "id": "portal",
        "name": "PORTAL",
        "motive": "Spacetime Shortcuts / Teleportation: A system for instant relocation across distance through spacetime shortcuts using stable, exotic-matter wormhole-like mechanisms.",
        "priority_reason": "Enables near-instant coordinate relocation bypassing physical transit.",
        "next_build": "Investigate Einstein-Rosen bridges, negative energy density stabilization, ER=EPR macro quantum state transfer, and earth rotation drift navigation.",
        "integration_role": "Kattappa AI OS maps source-destination coordinate fields and corrects orbital movement drift.",
        "safety_boundary": "Theoretical calculations only; biological preservation containment boundaries must remain fully active.",
        "free_tools": [
            "gemma",
            "git_cli_safety_workflow",
            "github_desktop",
            "local_eval_harness",
            "localsend",
            "sqlite_builtin_backend",
            "local_workflow_queue",
            "local_multi_agent_orchestrator",
            "mermaid",
        ],
        "path": str(PROJECTS_ROOT / "portal"),
    },
    {
        "rank": 12,
        "id": "mira",
        "name": "MIRA",
        "motive": "Matter Mapping & Atomic Reconstruction: A system capable of copying the exact sub-nanometer atomic structure of an object and recreating it elsewhere using available feedstock.",
        "priority_reason": "Enables high-fidelity matter replicating and programmatic self-assembly.",
        "next_build": "Deploy STM/AFM atomic scanning, compile chemical feedstock libraries, and design nanoscale programmatic self-assembly builders.",
        "integration_role": "Kattappa AI OS stores object blueprints and issues atomic printer commands.",
        "safety_boundary": "Reconstruction must use non-toxic, safe feedstock elements; zero copy-protection circumvention.",
        "free_tools": [
            "gemma",
            "git_cli_safety_workflow",
            "github_desktop",
            "local_eval_harness",
            "localsend",
            "sqlite_builtin_backend",
            "local_workflow_queue",
            "local_multi_agent_orchestrator",
            "mermaid",
        ],
        "path": str(PROJECTS_ROOT / "mira"),
    },
]


def project_ecosystem() -> dict[str, Any]:
    projects = []
    toolbox_patch = developer_toolbox_audit().get("free_project_applications_patch", {})
    for item in PROJECT_BLUEPRINTS:
        path = Path(item["path"])
        project_item = dict(item)
        project_item["free_tools"] = _merged_free_tools(
            item.get("free_tools", []),
            toolbox_patch.get(item["id"], []),
        )
        projects.append(
            {
                **project_item,
                "exists": path.exists(),
                "status": "present" if path.exists() else "missing",
            }
        )
    return {
        "strategy": "Build Kattappa AI OS first using the PDF ladder: LLM, RAG, agent, tool connections, approvals, automation, then use it as the central assistant for PCB Doctor, Cyber Shield, ULT, Musical Keyboard, safe DEWS, NeuroSeed, and the Spacetime & Matter Control Suite (Kairo, Prism, Tempo, Portal, Mira).",
        "build_first": "Kattappa AI OS v1: local-first chat, memory, Finance Brain, diagnostics, voice, wake-name commands, project-aware free-tool mapping, and cursor-guided desktop assistant.",
        "free_tool_rule": "Everything mapped into the seven projects must be fully free: free/open-source/local-first where practical, with no paid or freemium service dependency in the core project plan. If a named tool is paid, freemium, trial-limited, reward-based, closed, or privacy-risky, first search for a similar fully free replacement and add only the replacement when it improves a project.",
        "projects": projects,
    }


def _merged_free_tools(base: list[str], patch: list[str]) -> list[str]:
    merged = list(base)
    for tool in patch:
        if tool not in merged:
            merged.append(tool)
    return merged
